-- 001 — takeoff_projects
--
-- Per-user project rows for Takeoff Tooling. The schema is deliberately
-- column-for-column identical to Count Tooling's `projects` table (its 001
-- migration) so rows can be copied over at merge time. `id` is generated by
-- the client (crypto.randomUUID) so a project keeps one identity across
-- devices; `data` holds {manifest, laborRate}; `updated_at` mirrors the
-- client's savedAt and drives last-write-wins conflict resolution.
--
-- Until this is applied, the app runs local-only for projects (cloud.js
-- detects the missing table and disables project sync with a console note).
-- The existing takeoff_store table keeps the 'book' and 'assemblies' rows.

create table if not exists public.takeoff_projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Untitled project',
  data jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.takeoff_projects enable row level security;

create policy "Users can manage own takeoff projects"
  on public.takeoff_projects for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists takeoff_projects_user_id_idx on public.takeoff_projects(user_id);
create index if not exists takeoff_projects_updated_at_idx on public.takeoff_projects(updated_at desc);
